fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



test:
    pattern: /test
    defaults: { _controller: BSUserBundle:Test:index }


default:
    pattern:   /
    defaults:  { _controller: BSUserBundle:Default:index }


upload:
    pattern: /upload
    defaults: { _controller: BSUserBundle:Upload:upload }